name: 'PR Nomencleture'

description: 'Checks if PR is named as per input pattern'
author: Shivam 
branding:
  icon: clipboard
  color: blue

inputs:
  pattern:
    description: 'Keyword to match for deletion.'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:  
    - ${{ inputs.pattern }}