name: 'PR Nomencleture'

description: 'Checks if PR is named as per input pattern'
author: Shivam 
branding:
  icon: clipboard
  color: blue

inputs:
  token:
    description: 'GitHub token with repo scope.'
    required: true
  owner:
    description: 'owner of repo.'
    required: true
  repo:
    description: 'The name of the repository.'
    required: true
  pattern:
    description: 'Keyword to match for deletion.'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:  
    - ${{ inputs.token }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.pattern }}